### ISSUE TITLE
Praca domowa 2

### ISSUE THREAD

**Issue by BenC2611** [daftcode/frontend4beginners2018#12]
Hej,
Czy jeśli ktoś tu jeszcze dzisiaj jest, to mógłby mi podesłać formularz do przesłania zadania na bcelinski@poczta.pl? Nie było mnie na ostatnich zajęciach, stąd nie dostałem maila.
Z góry dzięki, jeśli ktoś pomoże :)

**Comment by Citrix94** [comment]
Podesłałem na maila ;)

**Comment by BenC2611** [comment]
Dzięki serdeczne :)
