### ISSUE TITLE
Formularz do pracy domowej nr 3

### ISSUE THREAD

**Issue by BenC2611** [daftcode/frontend4beginners2018#17]
Cześć!
Czy mógłbym prosić kogoś o przesłanie formularza na bcelinski@poczta.pl
Drugi raz go nie dostałem, a tym razem byłem na zajęciach :)
Z góry dzięki!

**Comment by Citrix94** [comment]
Wysłane ;)

**Comment by BenC2611** [comment]
Dzięki wielkie :)

**Comment by antonNina** [comment]
Czy ja też bym mogła prosić o wysłanie linku do formularza? Może być na antonantologic@gmail.com lub tutaj Z góry dziękuję! :-)

**Comment by Citrix94** [comment]
Poszło :)
