### ISSUE TITLE
Zadanie domowe sekcja Menu

### ISSUE THREAD

**Issue by AniaMoi** [daftcode/frontend4beginners2018#2]
Cześć właśnie robię zadanie domowe. Czy ktoś mógłby mi wytłumaczyć o co chodzi z menu/pressed; menu/active oraz z menu/default? Czy oni mają mieć jakąś funkcje (w sensie że coś wykonują) czy ma być listą?

**Comment by nekorushi** [comment]
Cześć, na chwilę obecną nie musisz się tym przejmować. Będziemy się tym zajmować na dalszych zajęciach.
Ogólnie te grafiki reprezentują link w różnych stanach (normalny, podświetlony po najechaniu myszką, podświetlony przy nawigacji klawiaturą, wciśnięty itp).

**Comment by AniaMoi** [comment]
Dziękuję za odpowiedź
